#!/bin/bash
set -euo pipefail

CONFIG_FILE=Config/OpenSource.xcconfig
DEFAULT_BUNDLE_ID=com.example.LaunchTroll

print_team_ids() {
  local xcode_prefs="$HOME/Library/Preferences/com.apple.dt.Xcode.plist"

  if [ ! -f "$xcode_prefs" ]; then
    return
  fi

  echo ""
  echo "Apple Developer teams found in Xcode preferences:"
  echo ""

  local team_keys
  team_keys=$(/usr/libexec/PlistBuddy -c "Print :IDEProvisioningTeams" "$xcode_prefs" 2>/dev/null | perl -lne 'print $1 if /^    (\S*) =/' || true)

  for key in $team_keys; do
    local index=0
    while true; do
      local name
      local team_id
      name=$(/usr/libexec/PlistBuddy -c "Print :IDEProvisioningTeams:$key:$index:teamName" "$xcode_prefs" 2>/dev/null) || break
      team_id=$(/usr/libexec/PlistBuddy -c "Print :IDEProvisioningTeams:$key:$index:teamID" "$xcode_prefs" 2>/dev/null) || break
      echo "$team_id - $name"
      index=$((index + 1))
    done
  done
}

if [ "${1:-}" = "" ]; then
  print_team_ids
  echo ""
  echo "> Apple Developer Team ID:"
  read -r TEAM_ID
else
  TEAM_ID=$1
fi

if [ -z "$TEAM_ID" ]; then
  echo "You must provide an Apple Developer Team ID."
  exit 1
fi

BUNDLE_ID=${2:-$DEFAULT_BUNDLE_ID}

mkdir -p "$(dirname "$CONFIG_FILE")"

{
  echo "// This file was generated by configure_team_id.sh and is intentionally ignored by git."
  echo ""
  echo "LAUNCHTROLL_BASE_BUNDLE_ID_OSS=$BUNDLE_ID"
  echo "LAUNCHTROLL_DEVELOPMENT_TEAM_OSS=$TEAM_ID"
} > "$CONFIG_FILE"

echo ""
echo "Generated $CONFIG_FILE"
echo "Team: $TEAM_ID"
echo "Bundle ID: $BUNDLE_ID"
